### PR TITLE
Create a study workflow

### LINKED ISSUE #13: Resource groups
- [x] Creation of study as part of setup
- [ ] Creation of a pod resource groups as part of setup.
- [ ] Removal of a pod (or study), when the work is completed.

### PR DESCRIPTION
**Pull request by pazdedav**
This PR contains two main files:

- new-studydeployment.ps1 (deployment script)
- newstudy.json (resource manager template for creating a study Resource Group and a storage account)

There is also a documentation describing the design.
**Please review** @gjersvik

### CODE REVIEW

**Comment by pazdedav** [comment]
I am adding more validation code to the script. Please do not merge yet. I will use **Draft PR** next time :-)

**Comment by gjersvik** [comment]
Just a quick look. But a small issue. Could you remove the .vs/ and add a rule to .gitignore to not take in your IDE config? You can just add a commit where you remove the files. No need to rebase them away. The solution file is fine.

Will download and try to run tomorrow.

**Comment by pazdedav** [comment]
I discovered a problem with storage name uniqueness when using subscription-level deployments (when you create a RG and a storage account in the same template).

I decided to **revert back to resource group-level deployment**, so I could use resourceGroup().id function for generating unique `storageAccountName`.

I also added several validations to PSH script:
- studyName parameter validation (ValidatePattern) to accept alphanumeric chars and underscore only.
- test if template file exist
- validate location parameter against available Azure regions (both name and DisplayName are accepted)
- validate, if entered subscriptionId is valid (i.e. logged on account has rights to it)
- validate, if Resource Group for entered studyName already exists, giving admin a choice to cancel the deployment

**Comment by pazdedav** [comment]
The code is **ready for your review** @gjersvik / @fmell . I tested all scenarios, e.g. input parameters validation.

**Review by fmell — APPROVED** [review]
Great work! Both deployment and validation works well. Is this ready to merge into master?

**Comment by pazdedav** [comment]
Thanks for your feedback @fmell . For my part, I believe it is ready to be merged. I was thinking about adding a Pester test script, but since this is an MVP, this could be added later. I will rather focus on the next workflow - "`PodSetup`".

**Comment by gjersvik** [comment]
Merged the into master great work @pazdedav.

**Pull request merged**
